tkg:
  regions:
    - name: tkg-region-vsphere-20200312184000
      context: tkg-region-vsphere-20200312184000-admin@tkg-region-vsphere-20200312184000
      file: /Users/anujc/.kube/config
    - name: tkg-region-aws-20200312192017
      context: tkg-region-aws-20200312192017-admin@tkg-region-aws-20200312192017
      file: /Users/anujc/.kube/config
  current-region-context: tkg-region-aws-20200312192017-admin@tkg-region-aws-20200312192017
providers:
  - name: "my-infra-provider"
    url: "https://github.com/myorg/myrepo/releases/latest/infrastructure_components.yaml"
    type: "InfrastructureProvider"
  - name: "cluster-api" # override a pre-defined provider
    url: "https://github.com/myorg/myforkofclusterapi/releases/latest/core_components.yaml"
    type: "CoreProvider"
  - name: aws
    url: /Users/dummy/.tkg/providers/infrastructure-aws/v0.5.1/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: /Users/dummy/.tkg/providers/infrastructure-vsphere/v0.6.2/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: /Users/dummy/.tkg/providers/infrastructure-vsphere/v0.7.0/infrastructure-components.yaml
    type: InfrastructureProvider

# Values for environment variable substitution
TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdXRENDQlVDZ0F3SUJBZ0lRQ2w4UlRRTmJGNUVYMHUvVUE0dy9PekFOQmdrcWhraUc5dzBCQVFVRkFEQnMKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1Tc3dLUVlEVlFRREV5SkVhV2RwUTJWeWRDQklhV2RvSUVGemMzVnlZVzVqClpTQkZWaUJTYjI5MElFTkJNQjRYRFRBNE1EUXdNakV5TURBd01Gb1hEVEl5TURRd016QXdNREF3TUZvd1pqRUwKTUFrR0ExVUVCaE1DVlZNeEZUQVRCZ05WQkFvVERFUnBaMmxEWlhKMElFbHVZekVaTUJjR0ExVUVDeE1RZDNkMwpMbVJwWjJsalpYSjBMbU52YlRFbE1DTUdBMVVFQXhNY1JHbG5hVU5sY25RZ1NHbG5hQ0JCYzNOMWNtRnVZMlVnClEwRXRNekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMOWhDaWtRSDE3K05EZFIKQ1BnZSt5THRZYjRMRFhCTVVHTW1kUlc1UVlpWHR2Q2dGYnNJWU9CQzZBVXBFSWMyaWlobHFPOHhCM1J0TnBjdgpLRVptQk1jcWVTWjZtZFdPdzIxUG9GNnR2RDJSd2xsN1hqWnN3RlBQQUFneVBoQmtXQkFUYWNjTTdweENVUUQ1CkJVVHVKTTU2SCsyTUViMFNxUE1WOUJ4Nk1Xa0JHNmZtWGNDYWJINEpudWRTUkVvUU9pUGttN1lEcjZpY3RGdWYKMUV1dGtvek90UkVxcWpjWWpiVEN1TmhjQm96NC95TzlOVjdVZkQ1K2d3NlJsZ1dZdzdJZjQ4aGw2Nmw3WGFBcwp6UHc4MlczdHpQcExRNHpKMUxpbFlSeXlRTFlvRXQrNStGLyswN0xKN3oyMEhrdDhIRXlaTnA0OTYreW5hRjRkCjMyZHVYdnNDQXdFQUFhT0NBdm93Z2dMMk1BNEdBMVVkRHdFQi93UUVBd0lCaGpDQ0FjWUdBMVVkSUFTQ0FiMHcKZ2dHNU1JSUJ0UVlMWUlaSUFZYjliQUVEQUFJd2dnR2tNRG9HQ0NzR0FRVUZCd0lCRmk1b2RIUndPaTh2ZDNkMwpMbVJwWjJsalpYSjBMbU52YlM5emMyd3RZM0J6TFhKbGNHOXphWFJ2Y25rdWFIUnRNSUlCWkFZSUt3WUJCUVVICkFnSXdnZ0ZXSG9JQlVnQkJBRzRBZVFBZ0FIVUFjd0JsQUNBQWJ3Qm1BQ0FBZEFCb0FHa0Fjd0FnQUVNQVpRQnkKQUhRQWFRQm1BR2tBWXdCaEFIUUFaUUFnQUdNQWJ3QnVBSE1BZEFCcEFIUUFkUUIwQUdVQWN3QWdBR0VBWXdCagpBR1VBY0FCMEFHRUFiZ0JqQUdVQUlBQnZBR1lBSUFCMEFHZ0FaUUFnQUVRQWFRQm5BR2tBUXdCbEFISUFkQUFnCkFFTUFVQUF2QUVNQVVBQlRBQ0FBWVFCdUFHUUFJQUIwQUdnQVpRQWdBRklBWlFCc0FIa0FhUUJ1QUdjQUlBQlEKQUdFQWNnQjBBSGtBSUFCQkFHY0FjZ0JsQUdVQWJRQmxBRzRBZEFBZ0FIY0FhQUJwQUdNQWFBQWdBR3dBYVFCdApBR2tBZEFBZ0FHd0FhUUJoQUdJQWFRQnNBR2tBZEFCNUFDQUFZUUJ1QUdRQUlBQmhBSElBWlFBZ0FHa0FiZ0JqCkFHOEFjZ0J3QUc4QWNnQmhBSFFBWlFCa0FDQUFhQUJsQUhJQVpRQnBBRzRBSUFCaUFIa0FJQUJ5QUdVQVpnQmwKQUhJQVpRQnVBR01BWlFBdU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdOQVlJS3dZQkJRVUhBUUVFS0RBbQpNQ1FHQ0NzR0FRVUZCekFCaGhob2RIUndPaTh2YjJOemNDNWthV2RwWTJWeWRDNWpiMjB3Z1k4R0ExVWRId1NCCmh6Q0JoREJBb0Q2Z1BJWTZhSFIwY0RvdkwyTnliRE11WkdsbmFXTmxjblF1WTI5dEwwUnBaMmxEWlhKMFNHbG4KYUVGemMzVnlZVzVqWlVWV1VtOXZkRU5CTG1OeWJEQkFvRDZnUElZNmFIUjBjRG92TDJOeWJEUXVaR2xuYVdObApjblF1WTI5dEwwUnBaMmxEWlhKMFNHbG5hRUZ6YzNWeVlXNWpaVVZXVW05dmRFTkJMbU55YkRBZkJnTlZIU01FCkdEQVdnQlN4UHNOcEEvaS9Sd0hVbUNZYUNBTHZZMlFyd3pBZEJnTlZIUTRFRmdRVVVPcHppZHNwK3hDUG51VUIKSU5UZWVabElnL2N3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUI3aXBVaWViTnRUT0EvdnBob3FyT0lEUSsyYQp2RDZPZFJ2dy9TNGlXYXdUd0dIaTUvcnBtYzJIQ1hWVUtMOUdZTnkrVVN5Uzh4dVJmREVJY09JM3VjRmJxTDJqCkN3RDdHaFg5QTYxWWFzWEhKSmxJUjBZeEhwTHZ0RjlPTk1lUXZ6SEIrTEdFaHRDY0FhcmZpbFlHempycERxNlgKZEYzWGNacENkRi9lalVOODN1bFY3V2tBeXdYZ2VtRmhNOUVaVGZrSTdxQTV4U1UxdHl2RUQ3TGQ4YVczRGlURQpKaWlOZVhmMUwvQlh1bndIMU9IOHpWb3dWMzZHRUVmZE1SL1gvS0xDdnpCOFhTU3E2UG11WDJwMHdzNXJzMGJZCkliNHAxSTVlRmRaQ1N1Y3liNlN4YTFHRFdMNC9iY2Y3MmdNaHkyb1dHVTRLOEsyRXlsMlVzMXAyOTJFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEeFRDQ0FxMmdBd0lCQWdJUUFxeGNKbW9MUUp1UEMzbnlya1lsZHpBTkJna3Foa2lHOXcwQkFRVUZBREJzCk1Rc3dDUVlEVlFRR0V3SlZVekVWTUJNR0ExVUVDaE1NUkdsbmFVTmxjblFnU1c1ak1Sa3dGd1lEVlFRTEV4QjMKZDNjdVpHbG5hV05sY25RdVkyOXRNU3N3S1FZRFZRUURFeUpFYVdkcFEyVnlkQ0JJYVdkb0lFRnpjM1Z5WVc1agpaU0JGVmlCU2IyOTBJRU5CTUI0WERUQTJNVEV4TURBd01EQXdNRm9YRFRNeE1URXhNREF3TURBd01Gb3diREVMCk1Ba0dBMVVFQmhNQ1ZWTXhGVEFUQmdOVkJBb1RERVJwWjJsRFpYSjBJRWx1WXpFWk1CY0dBMVVFQ3hNUWQzZDMKTG1ScFoybGpaWEowTG1OdmJURXJNQ2tHQTFVRUF4TWlSR2xuYVVObGNuUWdTR2xuYUNCQmMzTjFjbUZ1WTJVZwpSVllnVW05dmRDQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNYk01WFBtCis5Uzc1UzB0TXFiZjVZRS95YzBsU2JaeEtzUFZsRFJub2dvY3NGOXBwa0N4eExleWo5Q1lwS2xCV1RyVDNKVFcKUE50ME9LUkt6RTBsZ3ZkS3BWTVNPTzd6U1cxeGtYNWp0cXVtWDhPa2hQaFBZbEcrK01YczJ6aVM0d2JsQ0pFTQp4Q2hCVmZ2TFdva1ZmbkhvTmI5TmNnazl2am80VUZ0M01SdU5zOGNrUlpxbnJHMEFGRm9FdDdvVDYxRUttRUZCCklrNWxZWWVCUVZDbWVWeUozaGxLVjlVdTVsMGNVeXgrbU0wYUJoYWthSFBRTkFRVFhLRngwMXA4VmR0ZVpPRTMKaHpCV0JPVVJ0Q21BRXZGNU9ZaWlBaEY4SjJhM2lMZDQ4c29LcURpckNtVEN2MlpkbFlUQm9TVWVoMTBhVUFzZwpFc3hCdTI0TFVUaTRTOHNDQXdFQUFhTmpNR0V3RGdZRFZSMFBBUUgvQkFRREFnR0dNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkxFK3cya0QrTDlIQWRTWUpob0lBdTlqWkN2RE1COEdBMVVkSXdRWU1CYUEKRkxFK3cya0QrTDlIQWRTWUpob0lBdTlqWkN2RE1BMEdDU3FHU0liM0RRRUJCUVVBQTRJQkFRQWNHZ2FYM05lYwpuenlJWmdZSVZ5SGJJVWY0S21lcXZ4Z3lka0FRVjhHSzgzclpFV1dPTmZxZS9FVzFudGxNTVV1NGtlaERMSTZ6CmVNN2I0MU41Y2RibElaUUIybFdIbWlSazlvcG16TjZjTjgyb05MRnBteVBJbm5naUszQkQ0MVZITVdFWjcxakYKaFM5T01QYWdNUllqeU9maVpSWXp5NzhhRzZBOStNcGVpekdMWUFpSkxRd0dYRkszeFBrS21ORVZYNThTdm53MgpZemk5UktSLzVDWXJDc1NYYVEzcGpPTEFFRmU0eUhZU2tWWHlTR25ZdkNvQ1d3OUUxQ0F4Mi9TNmNDWmRrR0NlCnZFc1hDUysweXg1RGFNa0hKOEhTWFBmcUlibG9FcHc4bkwrZS9JQmNtMlBON0VlcUpTZG5vRGZ6QUlKOVZOZXAKK09rdUU2TjM2QjlLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY: true
AWS_B64ENCODED_CREDENTIALS: XXXXXXXX
VSPHERE_PASSWORD: Admin!23
KUBERNETES_VERSION: v1.16.0+vmware.1
BAR: bar
AWS_ACCESS_KEY_ID: <encoded:UVdSRVRZVUlPUExLSkhHRkRTQVo=>
AWS_SECRET_ACCESS_KEY: uNncCatIvWu1e$rqwerkg35qU7dswfEa4rdXJk/E
VSPHERE_DATACENTER: datacenter
VSPHERE_TEMPLATE: photon-3-v1.16.0+vmware.1
AWS_REGION: us-east-2
AWS_NODE_AZ: us-east-2a
AWS_AMI_ID: ami-xxxxx
AWS_VPC_CIDR: "10.0.0.0/16"
AWS_PRIVATE_NODE_CIDR: "10.0.0.0/24"
AWS_PUBLIC_NODE_CIDR: "10.0.1.0/24"
AWS_NODE_AZ_1: us-east-2b
AWS_PRIVATE_NODE_CIDR_1: "10.0.2.0/24"
AWS_PUBLIC_NODE_CIDR_1: "10.0.3.0/24"
AWS_NODE_AZ_2: us-east-2c
AWS_PRIVATE_NODE_CIDR_2: "10.0.4.0/24"
AWS_PUBLIC_NODE_CIDR_2: "10.0.5.0/24"
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "1"
VSPHERE_CONTROL_PLANE_MEM_MIB: "2048"
VSPHERE_WORKER_DISK_GIB: "20"
VSPHERE_WORKER_MEM_MIB: "2048"
VSPHERE_WORKER_NUM_CPUS: "1"
VSPHERE_HA_PROXY_MEM_MIB: "2048"
VSPHERE_HA_PROXY_DISK_GIB: "20"
VSPHERE_HA_PROXY_NUM_CPUS: "1"
WORKER_MACHINE_COUNT_0: "2"
WORKER_MACHINE_COUNT_1: "1"
WORKER_MACHINE_COUNT_2: "3"