TKG_KIND_AUDITING: true
providers:
  - name: cluster-api
    url: providers/cluster-api/v0.0.0/core-components.yaml
    type: CoreProvider
  - name: aws
    url: providers/infrastructure-aws/v0.5.1/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: providers/infrastructure-vsphere/v0.6.2/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere-pacific
    url: providers/infrastructure-tkg-service-vsphere/v1.0.0/unused.yaml
    type: InfrastructureProvider
  - name: kubeadm
    url: providers/bootstrap-kubeadm/v0.3.2/bootstrap-components.yaml
    type: BootstrapProvider
  - name: kubeadm
    url: providers/control-plane-kubeadm/v0.3.2/control-plane-components.yaml
    type: ControlPlaneProvider
