#@data/values
#@overlay/match-child-defaults missing_ok=True

---
infraProvider: null
calico:
  config:
    clusterCIDR: 192.168.0.0/16
    #! "1440" is default MTU that we set in TKG.
    #! https://docs.projectcalico.org/networking/mtu#determine-mtu-size
    #! Calico can autodetect MTU. Check if this can be set to null in the future.
    vethMTU: "1440"
  image:
    repository: docker.io
    pullPolicy: IfNotPresent
    tag: v3.16.6
  cniImage:
    repository: null
    path: calico/cni
    tag: null
    pullPolicy: null
  nodeImage:
    repository: null
    path: calico/node
    tag: null
    pullPolicy: null
  podDaemonImage:
    repository: null
    path: calico/pod2daemon-flexvol
    tag: null 
    pullPolicy: null
  kubeControllerImage:
    repository: null
    path: calico/kube-controllers
    tag: null
    pullPolicy: null
