#@data/values
#@overlay/match-child-defaults missing_ok=True

---
infraProvider: vsphere
antrea:
  config:
    serviceCIDR: 10.96.0.0/12
    trafficEncapMode: encap
    noSNAT: false
    #! Setting defaultMTU to null since antrea-agent will discover the MTU of the Node's primary interface and
    #! also adjust MTU to accommodate for tunnel encapsulation overhead.
    defaultMTU: null
    featureGates:
      AntreaProxy: false
      AntreaPolicy: true
      AntreaTraceflow: false
      FlowExporter: false
      NetworkPolicyStats: false
  image:
    repository: docker.io
    path: antrea/antrea-ubuntu 
    tag: v0.11.1
    pullPolicy: IfNotPresent
