apiVersion: run.tanzu.vmware.com/v1alpha3
kind: KappControllerConfig
metadata:
  name: v1.23.3---vmware.1-tkg.1
  namespace: tkg-system
spec:
  namespace: tkg-system
  kappController:
    globalNamespace: tkg-system
    deployment:
      apiPort: 10100
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
