#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"ClusterClass"})
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
spec:
  controlPlane:
    #@ if data.values.ENABLE_MHC or data.values.ENABLE_MHC_CONTROL_PLANE:
    #@overlay/match missing_ok=True
    machineHealthCheck:
      nodeStartupTimeout: #@ data.values.NODE_STARTUP_TIMEOUT
      unhealthyConditions:
      - type: Ready
        status: Unknown
        timeout: #@ data.values.MHC_UNKNOWN_STATUS_TIMEOUT
      - type: Ready
        status: "False"
        timeout: #@ data.values.MHC_FALSE_STATUS_TIMEOUT
      #@ end
  workers:
    machineDeployments:
    #@overlay/match by=overlay.index(0)
    - class: tkg-worker
      #@ if data.values.ENABLE_MHC or data.values.ENABLE_MHC_WORKER_NODE:
      #@overlay/match missing_ok=True
      machineHealthCheck:
        nodeStartupTimeout: #@ data.values.NODE_STARTUP_TIMEOUT
        unhealthyConditions:
        - type: Ready
          status: Unknown
          timeout: #@ data.values.MHC_UNKNOWN_STATUS_TIMEOUT
        - type: Ready
          status: "False"
          timeout: #@ data.values.MHC_FALSE_STATUS_TIMEOUT
        #@ end

#@overlay/match by=overlay.subset({"kind":"AzureClusterTemplate"})
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
spec:
  template:
    spec:
      azureEnvironment: #@ data.values.AZURE_ENVIRONMENT
      location: #@ data.values.AZURE_LOCATION
      subscriptionID: #@ data.values.AZURE_SUBSCRIPTION_ID

#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"}),expects="1+"
---
spec:
  #@overlay/match missing_ok=True
  template:
    #@overlay/match missing_ok=True
    spec:
      #@overlay/match missing_ok=True
      preKubeadmCommands:
      #@overlay/append
      - "if [ -f /etc/kubernetes/azure.json ]; then sed -i 's/\"vmType\": \"vmss\"/\"vmType\": \"standard\"/' /etc/kubernetes/azure.json; fi"

#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlaneTemplate"})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      kubeadmConfigSpec:
        #@overlay/match missing_ok=True
        preKubeadmCommands:
        #@overlay/append
        - "if [ -f /etc/kubernetes/azure.json ]; then sed -i 's/\"vmType\": \"vmss\"/\"vmType\": \"standard\"/' /etc/kubernetes/azure.json; fi"

#@overlay/match by=overlay.subset({"kind": "AzureMachineTemplate", "metadata":{"name": "tkg-controlplane-azure-template"}})
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
spec:
  template:
    spec:
      image:
        #@overlay/match missing_ok=True
        id: unknown
      sshPublicKey: #@ data.values.AZURE_SSH_PUBLIC_KEY_B64
      vmSize: #@ data.values.AZURE_CONTROL_PLANE_MACHINE_TYPE

#@overlay/match by=overlay.subset({"kind": "AzureMachineTemplate", "metadata":{"name": "tkg-azure-template"}})
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
spec:
  template:
    spec:
      image:
        #@overlay/match missing_ok=True
        id: unknown
      sshPublicKey: #@ data.values.AZURE_SSH_PUBLIC_KEY_B64
      vmSize: #@ data.values.AZURE_CONTROL_PLANE_MACHINE_TYPE