#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tkr-status-controller
  name: tkr-status-controller-manager
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tkr-service.tanzu.vmware.com/ClusterRoleBinding"
    kapp.k14s.io/change-rule.1: "delete before deleting tkr-service.tanzu.vmware.com/ClusterRoleBinding"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tkr-status-controller
  template:
    metadata:
      labels:
        app: tkr-status-controller
    spec:
      containers:
        - image: tkr-status-controller:latest
          imagePullPolicy: IfNotPresent
          name: manager
          command:
            - /manager
          args:
            - --metrics-bind-addr=0
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccount: tkr-service-manager-sa
      terminationGracePeriodSeconds: 10
      #@ if hasattr(data.values, 'deployment') and hasattr(data.values.deployment, 'hostNetwork') and data.values.deployment.hostNetwork:
      #@overlay/match missing_ok=True
      hostNetwork: true
      #@ end
      #@ if hasattr(data.values, 'deployment') and hasattr(data.values.deployment, 'tolerations') and data.values.deployment.tolerations:
      #@overlay/match missing_ok=True
      tolerations: #@ data.values.deployment.tolerations
      #@ end
      #@ if hasattr(data.values, 'deployment') and hasattr(data.values.deployment, 'nodeSelector') and data.values.deployment.nodeSelector:
      #@overlay/match missing_ok=True
      nodeSelector: #@ data.values.deployment.nodeSelector
      #@ end
