apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: tanzu-system/tkr-resolver-cluster-webhook-serving-cert
  name: tkr-cluster-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: tkr-resolver-cluster-webhook-service
      namespace: tanzu-system
      path: /mutate-cluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: tkr-resolver-cluster-webhook.tanzu.vmware.com
  rules:
  - apiGroups: ["cluster.x-k8s.io"]
    apiVersions:
    - v1
    - v1beta1
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - "clusters"
  sideEffects: None