---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: antreaconfigs.cni.tanzu.vmware.com
spec:
  group: cni.tanzu.vmware.com
  names:
    kind: AntreaConfig
    listKind: AntreaConfigList
    plural: antreaconfigs
    shortNames:
    - antreaconf
    singular: antreaconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The traffic encapsulation mode. One of the following options =>
        encap, noEncap, hybrid, networkPolicyOnly
      jsonPath: .spec.antrea.config.trafficEncapMode
      name: TrafficEncapMode
      type: string
    - description: Default MTU to use for the host gateway interface and the network
        interface of each Pod. If omitted, antrea-agent will discover the MTU of the
        Node's primary interface
      jsonPath: .spec.antrea.config.defaultMTU
      name: DefaultMTU
      type: string
    - description: Flag to enable/disable antrea proxy
      jsonPath: .spec.antrea.config.featureGates.AntreaProxy
      name: AntreaProxy
      type: string
    - description: Flag to enable/disable antrea policy
      jsonPath: .spec.antrea.config.featureGates.AntreaPolicy
      name: AntreaPolicy
      type: string
    - description: Name of the antrea data values secret
      jsonPath: .status.secretRef
      name: SecretRef
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AntreaConfig is the Schema for the antreaconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AntreaConfigSpec defines the desired state of AntreaConfig
            properties:
              antrea:
                properties:
                  config:
                    properties:
                      antreaProxy:
                        description: Specifies AntreaProxy related configuration.
                        properties:
                          nodePortAddresses:
                            items:
                              type: string
                            type: array
                          proxyAll:
                            type: boolean
                          proxyLoadBalancerIPs:
                            type: boolean
                          skipServices:
                            items:
                              type: string
                            type: array
                        type: object
                      defaultMTU:
                        default: ""
                        description: Default MTU to use for the host gateway interface
                          and the network interface of each Pod. If omitted, antrea-agent
                          will discover the MTU of the Node's primary interface
                        type: string
                      disableUdpTunnelOffload:
                        default: false
                        description: Disable UDP tunnel offload feature on default
                          NIC
                        type: boolean
                      egress:
                        description: Specifies Egress related configuration.
                        properties:
                          exceptCIDRs:
                            items:
                              type: string
                            type: array
                        type: object
                      enableUsageReporting:
                        default: false
                        description: Enable usage reporting (telemetry) to VMware.
                        type: boolean
                      featureGates:
                        description: FeatureGates is a map of feature names to flags
                          that enable or disable experimental features
                        properties:
                          AntreaIPAM:
                            default: false
                            description: Flag to enable/disable antrea IPAM
                            type: boolean
                          AntreaPolicy:
                            default: true
                            description: Flag to enable/disable antrea policy
                            type: boolean
                          AntreaProxy:
                            default: true
                            description: Flag to enable/disable antrea proxy
                            type: boolean
                          AntreaTraceflow:
                            default: true
                            description: Flag to enable/disable antrea traceflow
                            type: boolean
                          Egress:
                            default: true
                            description: Flag to enable/disable SNAT IPs of Pod egress
                              traffic
                            type: boolean
                          EndpointSlice:
                            default: false
                            description: Flag to enable/disable EndpointSlice support
                              in AntreaProxy. If AntreaProxy is not enabled, this
                              flag will not take effect
                            type: boolean
                          FlowExporter:
                            default: false
                            description: Flag to enable/disable flow exporter
                            type: boolean
                          Multicast:
                            default: false
                            description: Flag to enable/disable multicast
                            type: boolean
                          NetworkPolicyStats:
                            default: false
                            description: Flag to enable/disable network policy stats
                            type: boolean
                          NodePortLocal:
                            default: true
                            description: Flag to enable/disable NodePortLocal feature
                              to make the pods reachable externally through NodePort
                            type: boolean
                          ServiceExternalIP:
                            default: false
                            description: Flag to enable/disable service external IP
                            type: boolean
                        type: object
                      flowExporter:
                        description: Specifies FlowExporter related configuration.
                        properties:
                          activeFlowTimeout:
                            type: string
                          collectorAddress:
                            type: string
                          idleFlowTimeout:
                            type: string
                          pollInterval:
                            type: string
                        type: object
                      kubeAPIServerOverride:
                        description: Provide the address of Kubernetes apiserver,
                          to override any value provided in kubeconfig or InClusterConfig.
                        type: string
                      multicastInterfaces:
                        description: The names of the interfaces on Nodes that are
                          used to forward multicast traffic.
                        items:
                          type: string
                        type: array
                      noSNAT:
                        default: false
                        description: Flag to enable/disable SNAT for the egress traffic
                          from a Pod to the external network
                        type: boolean
                      nodePortLocal:
                        description: Specifies NodePortLocal related configuration.
                        properties:
                          enabled:
                            type: boolean
                          portRange:
                            type: string
                        type: object
                      serviceCIDR:
                        description: ClusterIP CIDR range for Services.
                        type: string
                      tlsCipherSuites:
                        default: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
                        description: List of allowed cipher suites. If omitted, the
                          default Go Cipher Suites will be used
                        type: string
                      trafficEncapMode:
                        default: encap
                        description: The traffic encapsulation mode. One of the following
                          options => encap, noEncap, hybrid, networkPolicyOnly
                        enum:
                        - encap
                        - noEncap
                        - hybrid
                        - networkPolicyOnly
                        type: string
                      trafficEncryptionMode:
                        description: Determines how tunnel traffic is encrypted. One
                          of the following options =:> none, ipsec, wireguard
                        type: string
                      transportInterface:
                        description: The name of the interface on Node which is used
                          for tunneling or routing.
                        type: string
                      transportInterfaceCIDRs:
                        description: The network CIDRs of the interface on Node which
                          is used for tunneling or routing.
                        items:
                          type: string
                        type: array
                      tunnelType:
                        description: Tunnel protocols used for encapsulating traffic
                          across Nodes. One of the following options =:> geneve, vxlan,
                          gre, stt
                        type: string
                      wireGuard:
                        description: Specifies WireGuard related configuration.
                        properties:
                          port:
                            type: integer
                        type: object
                    type: object
                type: object
            type: object
          status:
            description: AntreaConfigStatus defines the observed state of AntreaConfig
            properties:
              secretRef:
                description: Reference to the data value secret created by controller
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
