providers:
- name: cluster-api
  url: providers/cluster-api/v1.2.6/core-components.yaml
  type: CoreProvider
- name: aws
  url: providers/infrastructure-aws/v2.0.1/infrastructure-components.yaml
  type: InfrastructureProvider
- name: vsphere
  url: providers/infrastructure-vsphere/v1.5.0/infrastructure-components.yaml
  type: InfrastructureProvider
- name: azure
  url: providers/infrastructure-azure/v1.5.3/infrastructure-components.yaml
  type: InfrastructureProvider
- name: tkg-service-vsphere
  url: providers/infrastructure-tkg-service-vsphere/v1.1.0/unused.yaml
  type: InfrastructureProvider
- name: oci
  url: providers/infrastructure-oci/v0.4.0/infrastructure-components.yaml
  type: InfrastructureProvider
- name: kubeadm
  url: providers/bootstrap-kubeadm/v1.2.6/bootstrap-components.yaml
  type: BootstrapProvider
- name: kubeadm
  url: providers/control-plane-kubeadm/v1.2.6/control-plane-components.yaml
  type: ControlPlaneProvider
- name: docker
  url: providers/infrastructure-docker/v1.2.6/infrastructure-components.yaml
  type: InfrastructureProvider
cert-manager:
  url: providers/cert-manager/v1.9.1/cert-manager.yaml
  version: "v1.9.1"
