#@data/values

#@overlay/match-child-defaults missing_ok=True
---

#! User configurable values for tkg-autoscaler

CLUSTER_NAME: ""
NAMESPACE:
AUTOSCALER_MAX_NODES_TOTAL: "0"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_ADD: "10m"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_DELETE: "10s"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_FAILURE: "3m"
AUTOSCALER_SCALE_DOWN_UNNEEDED_TIME: "10m"
AUTOSCALER_MAX_NODE_PROVISION_TIME: "15m"
TKG_CLUSTER_ROLE:
PROVIDER_TYPE:
