---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: kubevipcpconfigs.lb.tanzu.vmware.com
spec:
  group: lb.tanzu.vmware.com
  names:
    kind: KubevipCPConfig
    listKind: KubevipCPConfigList
    plural: kubevipcpconfigs
    singular: kubevipcpconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KubevipCPConfig is the Schema for the kubevipcpconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KubevipCPConfigSpec defines the desired state of KubevipCPConfig
            properties:
              loadbalancerCIDRs:
                description: loadbalancerCIDRs is a list of comma separated
                  cidrs will be used to allocate IP for external load balancer. For
                  example 192.168.0.200/29,192.168.1.200/29
                type: string
              loadbalancerIPRanges:
                description: loadbalancerIPRanges is a list of comma separated IP
                  ranges will be used to allocate IP for external load balancer. For
                  example 192.168.0.10-192.168.0.11,192.168.0.10-192.168.0.13
                type: string
            type: object
          status:
            description: KubevipCPConfigStatus defines the observed state of KubevipCPConfig
            properties:
              secretRef:
                description: Name of the secret created by kubevip cloudprovider config
                  controller
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
