#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tkr-source-controller
  name: tkr-source-controller-manager-sa
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "tkr-source-controller.tanzu.vmware.com/serviceaccount"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tkr-source-controller-manager-role
  annotations:
    kapp.k14s.io/change-group: "tkr-source-controller.tanzu.vmware.com/serviceaccount"
rules:
  #!  RBAC rules to create PackageInstall CR and service accounts
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tkr-source-controller-manager-clusterrolebinding
  annotations:
    kapp.k14s.io/change-group: "tkr-source-controller.tanzu.vmware.com/ClusterRoleBinding"
    kapp.k14s.io/change-rule.0: "upsert after upserting tkr-source-controller.tanzu.vmware.com/serviceaccount"
    kapp.k14s.io/change-rule.1: "delete before deleting tkr-source-controller.tanzu.vmware.com/serviceaccount"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tkr-source-controller-manager-role
subjects:
- kind: ServiceAccount
  name: tkr-source-controller-manager-sa
  namespace: #@ data.values.namespace
