#@data/values
#@overlay/match-child-defaults missing_ok=True

---
tanzuAddonsManager:
  namespace: tkg-system
  createNamespace: true
  deployment:
    hostNetwork: true
    priorityClassName: null
    nodeSelector: null
    tolerations: []
    webhookServerPort: 9865
    healthzPort: 18316
    metricsBindAddress: "localhost:18317"
  featureGates:
    clusterBootstrapController: false
    packageInstallStatus: false
