#@data/values

#@overlay/match-child-defaults missing_ok=True
---

#! User configurable values for tkg-clusterclass-azure

ENABLE_MHC: ""
ENABLE_MHC_CONTROL_PLANE: ""
ENABLE_MHC_WORKER_NODE: ""
MHC_FALSE_STATUS_TIMEOUT: ""
MHC_UNKNOWN_STATUS_TIMEOUT: ""
NODE_STARTUP_TIMEOUT: ""
NAMESPACE: tkg-system
AZURE_ENVIRONMENT: ""
AZURE_LOCATION: ""
AZURE_VNET_CIDR: ""
AZURE_CONTROL_PLANE_SUBNET_NAME: management-cluster-controlplane-subnet
AZURE_CONTROL_PLANE_SUBNET_CIDR: ""
AZURE_NODE_SUBNET_NAME: management-cluster-node-subnet
AZURE_NODE_SUBNET_CIDR: ""
AZURE_SUBSCRIPTION_ID: ""
