#@data/values
#@overlay/match-child-defaults missing_ok=True

---
vsphereCSI:
  CSIAttacherImage:
    repository: "quay.io/k8scsi"
    path: "csi-attacher"
    tag: v3.0.0
    pullPolicy: "IfNotPresent"
  vsphereCSIControllerImage:
    repository: "gcr.io/cloud-provider-vsphere"
    path: "csi/release/driver"
    tag: v2.1.0
    pullPolicy: "IfNotPresent"
  livenessProbeImage:
    repository: "quay.io/k8scsi"
    path: "livenessprobe"
    tag: v2.1.0
    pullPolicy: "IfNotPresent"
  vsphereSyncerImage:
    repository: "gcr.io/cloud-provider-vsphere"
    path: "csi/release/syncer"
    tag: v2.1.0
    pullPolicy: "IfNotPresent"
  CSIProvisionerImage:
    repository: "quay.io/k8scsi"
    path: "csi-provisioner"
    tag: v2.0.0
    pullPolicy: "IfNotPresent"
  CSINodeDriverRegistrarImage:
    repository: "quay.io/k8scsi"
    path: "csi-node-driver-registrar"
    tag: v2.0.1
    pullPolicy: "IfNotPresent"
