#@data/values
---

#! User configurable values for tkg-clusterclass.

namespaceForPackageInstallation: tkg-system
clusterclassInfraPackageValues:
  namespace: tkg-system
  infraProvider: ""
  configValues:
  versionConstraints:
