#@ load("@ytt:data", "data")

#@ if data.values.tanzuAddonsManager.createNamespace:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.tanzuAddonsManager.namespace
#@ end
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tanzu-addons-manager
  name: tanzu-addons-manager-sa
  namespace: #@ data.values.tanzuAddonsManager.namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-addons-manager-clusterrole
rules:
- apiGroups:
  - run.tanzu.vmware.com
  resources:
  - tanzukubernetesreleases
  - tanzukubernetesreleases/status
  - clusterbootstraps
  - clusterbootstraptemplates
  - kappcontrollerconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cni.tanzu.vmware.com
  resources:
  - antreaconfigs
  - calicoconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
#! permissions are required for addons-manager to reconcile vspherecpiconfigs and CPI related service accounts
- apiGroups:
  - cpi.tanzu.vmware.com
  resources:
  - vspherecpiconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cpi.tanzu.vmware.com
  resources:
  - vspherecpiconfigs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - vmware.infrastructure.cluster.x-k8s.io
  resources:
  - providerserviceaccounts
  verbs:
  - get
  - create
  - list
  - watch
  - update
  - patch
#! permissions are required for addons-manager to reconcile vspherecsiconfigs and CSI related service accounts
- apiGroups:
  - csi.tanzu.vmware.com
  resources:
  - vspherecsiconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - csi.tanzu.vmware.com
  resources:
  - vspherecsiconfigs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - vmware.infrastructure.cluster.x-k8s.io
  resources:
  - providerserviceaccounts
  verbs:
  - get
  - create
  - list
  - watch
  - update
  - patch
#! permissions are required for addons-manager to create/update resources in the ProviderRef which are dynamic.
- apiGroups: ['*']
  resources: ['*']
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes
  - kubeadmcontrolplanes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - kappctrl.k14s.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - packaging.carvel.dev
  resources:
  - packagerepositories
  - packagerepositories/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - packaging.carvel.dev
  resources:
  - packageinstalls
  - packageinstalls/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-addons-manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-addons-manager-clusterrole
subjects:
- kind: ServiceAccount
  name: tanzu-addons-manager-sa
  namespace: #@ data.values.tanzuAddonsManager.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tanzu-addons-manager
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting addons.config.tanzu.vmware.com/webhook"
    kapp.k14s.io/change-rule.1: "delete before deleting addons.config.tanzu.vmware.com/webhook"
  name: tanzu-addons-controller-manager
  namespace: #@ data.values.tanzuAddonsManager.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanzu-addons-manager
  template:
    metadata:
      labels:
        app: tanzu-addons-manager
    spec:
      #@ if/end data.values.tanzuAddonsManager.deployment.nodeSelector:
      nodeSelector: #@ data.values.tanzuAddonsManager.deployment.nodeSelector
      containers:
      - args:
        - --metrics-bind-addr=0
        - --leader-elect=false
        - --health-addr=:18316
        - #@ "--addon-namespace={}".format(data.values.tanzuAddonsManager.namespace)
        #@ if/end data.values.tanzuAddonsManager.featureGates.clusterBootstrapController:
        - --feature-gate-cluster-bootstrap=true
        image: addons-controller:latest
        imagePullPolicy: IfNotPresent
        name: tanzu-addons-controller
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 40Mi
        ports:
          - containerPort: 9865
            name: webhook-server
            protocol: TCP
          - containerPort: 18316
            name: healthz
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        startupProbe:
          httpGet:
            path: /healthz
            port: healthz
          failureThreshold: 60
          periodSeconds: 10
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccount: tanzu-addons-manager-sa
      terminationGracePeriodSeconds: 10
      #@ if/end data.values.tanzuAddonsManager.deployment.hostNetwork:
      hostNetwork: true
      #@ if/end data.values.tanzuAddonsManager.deployment.priorityClassName:
      priorityClassName: #@ data.values.tanzuAddonsManager.deployment.priorityClassName
      #@ if/end hasattr(data.values.tanzuAddonsManager.deployment, 'tolerations') and data.values.tanzuAddonsManager.deployment.tolerations:
      tolerations: #@ data.values.tanzuAddonsManager.deployment.tolerations
