#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: cli.tanzu.vmware.com/v1alpha1
kind: CLIPlugin
metadata:
  creationTimestamp: null
  name: management-cluster
spec:
  artifacts:
    #@yaml/text-templated-strings
    (@= data.values.managementcluster.version @):
    - arch: amd64
      image: tanzu-cli-plugins/management-cluster-darwin-amd64:latest
      os: darwin
      type: oci
    - arch: amd64
      image: tanzu-cli-plugins/management-cluster-linux-amd64:latest
      os: linux
      type: oci
    - arch: amd64
      image: tanzu-cli-plugins/management-cluster-windows-amd64:latest
      os: windows
      type: oci
  description: Kubernetes management-cluster operations
  optional: false
  recommendedVersion: #@ data.values.managementcluster.version
  target: kubernetes
