#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: cli.tanzu.vmware.com/v1alpha1
kind: CLIPlugin
metadata:
  creationTimestamp: null
  name: secret
spec:
  artifacts:
    #@yaml/text-templated-strings
    (@= data.values.secret.version @):
    - arch: amd64
      image: tanzu-cli-plugins/secret-darwin-amd64:latest
      os: darwin
      type: oci
    - arch: amd64
      image: tanzu-cli-plugins/secret-linux-amd64:latest
      os: linux
      type: oci
    - arch: amd64
      image: tanzu-cli-plugins/secret-windows-amd64:latest
      os: windows
      type: oci
  description: Tanzu secret management
  optional: false
  recommendedVersion: #@ data.values.secret.version
  target: k8s
