#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: cli.tanzu.vmware.com/v1alpha1
kind: CLIPlugin
metadata:
  name: telemetry
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting cliplugins.cli.tanzu.vmware.com/crd"
spec:
  artifacts:
    #@yaml/text-templated-strings
    (@= data.values.telemetry.version @):
      - arch: amd64
        image: tanzu-cli-plugins/telemetry-darwin-amd64:latest
        os: darwin
        type: oci
      - arch: amd64
        image: tanzu-cli-plugins/telemetry-linux-amd64:latest
        os: linux
        type: oci
      - arch: amd64
        image: tanzu-cli-plugins/telemetry-windows-amd64:latest
        os: windows
        type: oci
  description: Configure cluster-wide telemetry settings
  optional: false
  recommendedVersion: #@ data.values.telemetry.version
  target: k8s
