#@data/values
#@overlay/match-child-defaults missing_ok=True

---
vsphereCPI:
  tlsThumbprint: ""
  server: null
  datacenter: null
  username: null
  password: null
  insecureFlag: False
  ipFamily: null
  vmInternalNetwork: null
  vmExternalNetwork: null
  image:
    repository: "projects-stg.registry.vmware.com/tkg"
    path: "cloud-provider-vsphere/cpi/release/manager"
    tag: v1.2.1
    pullPolicy: "IfNotPresent"
  cloudProviderExtraArgs:
    tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  nsxt:
    podRoutingEnabled: false
    routes:
      routerPath: ""
    username: ""
    password: ""
    host: null
    insecureFlag: "false"
    remoteAuth: "false"
    vmcAccessToken: ""
    vmcAuthHost: ""
    clientCertKeyData: ""
    clientCertData: ""
    rootCAData: ""
    secretName: "cloud-provider-vsphere-nsxt-credentials"
    secretNamespace: "kube-system"
