apiVersion: lb.tanzu.vmware.com/v1alpha1
kind: KubevipCPConfig
metadata:
  name: v1.23.3---vmware.1-tkg.1
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/template-config: "true"
spec:
  loadbalancerIPRanges: ""
  loadbalancerCIDRs: ""
