#@data/values
#@overlay/match-child-defaults missing_ok=True
---
namespaceForPackageInstallation:
featureGatesPackageValues:
  namespace:
  versionConstraints:
  deployment:
    hostNetwork: true
    nodeSelector: null
    tolerations: []
tkrServicePackageValues:
  namespace:
  versionConstraints:
addonsManagerPackageValues:
  versionConstraints:
  tanzuAddonsManager:
    namespace: tkg-system
    createNamespace: false
    deployment:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      nodeSelector: null
      tolerations: []
      healthzPort: 18316
    featureGates:
      clusterBootstrapController: false
clipluginsPackageValues:
  namespace:
  versionConstraints:
