#@ load("@ytt:data", "data")

#@ def webhook_manifests():
---
apiVersion: v1
kind: Service
metadata:
  name: tanzu-addons-manager-webhook-service
  namespace: #@ data.values.tanzuAddonsManager.namespace
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    app: tanzu-addons-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    tkg.tanzu.vmware.com/addon-webhooks: "addon-webhooks"
  annotations:
    kapp.k14s.io/change-group: "addons.config.tanzu.vmware.com/webhook"
  name: tkg-cni-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: tanzu-addons-manager-webhook-service
        namespace: #@ data.values.tanzuAddonsManager.namespace
        path: /validate-cni-tanzu-vmware-com-v1alpha1-antreaconfig
    failurePolicy: Fail
    name: antreaconfig.validating.vmware.com
    rules:
      - apiGroups:
          - cni.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - antreaconfigs
    sideEffects: None
    timeoutSeconds: 30
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: tanzu-addons-manager-webhook-service
        namespace: #@ data.values.tanzuAddonsManager.namespace
        path: /validate-cni-tanzu-vmware-com-v1alpha1-calicoconfig
    failurePolicy: Fail
    name: calicoconfig.validating.vmware.com
    rules:
      - apiGroups:
          - cni.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - calicoconfigs
    sideEffects: None
    timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    tkg.tanzu.vmware.com/addon-webhooks: "addon-webhooks"
  annotations:
    kapp.k14s.io/change-group: "addons.config.tanzu.vmware.com/webhook"
  name: clusterbootstrap-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: tanzu-addons-manager-webhook-service
        namespace: #@ data.values.tanzuAddonsManager.namespace
        path: /mutate-run-tanzu-vmware-com-v1alpha3-clusterbootstrap
    failurePolicy: Fail
    name: clusterbootstrap.mutating.vmware.com
    rules:
      - apiGroups:
          - run.tanzu.vmware.com
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterbootstraps
    sideEffects: None
    timeoutSeconds: 30
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: tanzu-addons-manager-webhook-service
        namespace: #@ data.values.tanzuAddonsManager.namespace
        path: /mutate-cluster-x-k8s-io-v1beta1-cluster
    failurePolicy: Fail
    name: clusterpause.mutating.vmware.com
    rules:
      - apiGroups:
          - cluster.x-k8s.io
        apiVersions:
          - v1beta1
        operations:
          - UPDATE
        resources:
          - clusters
    sideEffects: None
    timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    tkg.tanzu.vmware.com/addon-webhooks: "addon-webhooks"
  annotations:
    kapp.k14s.io/change-group: "addons.config.tanzu.vmware.com/webhook"
  name: clusterbootstrap-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: tanzu-addons-manager-webhook-service
        namespace: #@ data.values.tanzuAddonsManager.namespace
        path: /validate-run-tanzu-vmware-com-v1alpha3-clusterbootstrap
    failurePolicy: Fail
    name: clusterbootstrap.validating.vmware.com
    rules:
      - apiGroups:
          - run.tanzu.vmware.com
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterbootstraps
    sideEffects: None
    timeoutSeconds: 30
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: tanzu-addons-manager-webhook-service
        namespace: #@ data.values.tanzuAddonsManager.namespace
        path: /validate-run-tanzu-vmware-com-v1alpha3-clusterbootstraptemplate
    failurePolicy: Fail
    name: clusterbootstraptemplate.validating.vmware.com
    rules:
      - apiGroups:
          - run.tanzu.vmware.com
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterbootstraptemplates
    sideEffects: None
    timeoutSeconds: 30

#@ end
