#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
#@ if data.values.akoOperatorPackage.akoOperator.avi_enable:
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: ako-operator-v2
  namespace: tkg-system
  labels:
    tkg.tanzu.vmware.com/package-type: "management"
spec:
  packageRef:
    refName: ako-operator-v2.tanzu.vmware.com
    versionSelection:
      prereleases: {}
  serviceAccountName: ako-operator-v2-package-sa
  values:
    - secretRef:
        name: ako-operator-v2-values
---
apiVersion: v1
kind: Secret
metadata:
  name: ako-operator-v2-values
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting ako-operator-v2-packageinstall/serviceaccount"
    kapp.k14s.io/change-rule.1: "delete before deleting ako-operator-v2-packageinstall/serviceaccount"
type: Opaque
stringData:
  values.yaml: #@ yaml.encode(data.values.akoOperatorPackage)
#@ end
