#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
#@ if data.values.akoOperatorPackage.akoOperator.avi_enable:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-balancer-and-ingress-service-package-sa
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-group: "load-balancer-and-ingress-service-packageinstall/serviceaccount-0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: load-balancer-and-ingress-service-package-role
  annotations:
    kapp.k14s.io/change-group: "load-balancer-and-ingress-service-packageinstall/serviceaccount-0"
rules:
  #  RBAC rules to create PackageInstall CR and service accounts
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: load-balancer-and-ingress-service-package-cluster-rolebinding
  annotations:
    kapp.k14s.io/change-group: "load-balancer-and-ingress-service-packageinstall/serviceaccount"
    kapp.k14s.io/change-rule.0: "upsert after upserting load-balancer-and-ingress-service-packageinstall/serviceaccount-0"
    kapp.k14s.io/change-rule.1: "delete before deleting load-balancer-and-ingress-service-packageinstall/serviceaccount-0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: load-balancer-and-ingress-service-package-role
subjects:
  - kind: ServiceAccount
    name: load-balancer-and-ingress-service-package-sa
    namespace: tkg-system
#@ end
