
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: features.config.tanzu.vmware.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.activated
    name: Activated
    type: boolean
  - JSONPath: .spec.description
    name: Description
    type: string
  - JSONPath: .spec.immutable
    name: Immutable
    type: boolean
  - JSONPath: .spec.maturity
    name: Maturity
    type: string
  group: config.tanzu.vmware.com
  names:
    kind: Feature
    listKind: FeatureList
    plural: features
    singular: feature
  scope: Cluster
  subresources: {}
  validation:
    openAPIV3Schema:
      description: Feature is the Schema for the features API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FeatureSpec defines the desired state of Feature
          properties:
            activated:
              description: Activated defines the default state of the features activation
              type: boolean
            description:
              description: Description of the feature.
              type: string
            discoverable:
              description: Discoverable indicates if clients should include consider
                the Feature available for their use Allowing clients to control discoverability
                is one of the ways the API allows gradual rollout of functionality
              type: boolean
            immutable:
              description: Immutable indicates this feature cannot be toggled once
                set If set at creation time, this state will persist for the life
                of the cluster
              type: boolean
            maturity:
              description: 'Maturity indicates maturity level of this feature. Maturity
                levels are Dev, Alpha, Beta, GA and Deprecated. - dev: the default
                for new resources, represents local dev. intended to be hidden and
                deactivated - alpha: the first milestone meant for limited wider consumption,
                discoverable and defaults to deactivated - beta: greater visibility
                for proven designs, discoverable and defaults to activated - ga: intended
                to be part of the mainline codebase, non-optional - deprecated: destined
                for future removal'
              enum:
              - dev
              - alpha
              - beta
              - ga
              - deprecated
              type: string
          required:
          - activated
          - discoverable
          - immutable
          - maturity
          type: object
        status:
          description: FeatureStatus defines the observed state of Feature
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
