---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: vspherecpiconfigs.cpi.tanzu.vmware.com
spec:
  group: cpi.tanzu.vmware.com
  names:
    kind: VSphereCPIConfig
    listKind: VSphereCPIConfigList
    plural: vspherecpiconfigs
    shortNames:
    - vcpic
    singular: vspherecpiconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The name of the VSphereCPIConfig
      jsonPath: .spec.namespace
      name: Name
      type: string
    - description: Name of the kapp-controller data values secret
      jsonPath: .spec.vsphereCPI.mode
      name: Mode
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VSphereCPIConfig is the Schema for the VSphereCPIConfig API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VSphereCPIConfigSpec defines the desired state of VSphereCPIConfig
            properties:
              vsphereCPI:
                properties:
                  antreaNSXPodRoutingEnabled:
                    default: false
                    description: A flag that enables pod routing by Antrea NSX for
                      paravirtual mode
                    type: boolean
                  datacenter:
                    description: The datacenter in which VMs are created/located
                    type: string
                  insecure:
                    default: false
                    description: The flag that disables TLS peer verification
                    type: boolean
                  ipFamily:
                    description: The IP family configuration
                    enum:
                    - ipv4
                    - ipv6
                    - ipv4,ipv6
                    - ipv6,ipv4
                    type: string
                  mode:
                    description: The vSphere mode. Either `vsphereCPI` or `vsphereParavirtualCPI`.
                    enum:
                    - vsphereCPI
                    - vsphereParavirtualCPI
                    type: string
                  nsxt:
                    properties:
                      apiHost:
                        description: The NSX-T server
                        type: string
                      clientCertData:
                        description: Client certificate data for NSX-T
                        type: string
                      clientCertKeyData:
                        description: Client certificate key for NSX-T
                        type: string
                      credentialLocalObjRef:
                        description: A secret reference that contains Nsx-T login
                          credential to access NSX-T consists of the field username
                          and password
                        properties:
                          apiGroup:
                            description: APIGroup is the group for the resource being
                              referenced. If APIGroup is not specified, the specified
                              Kind must be in the core API group. For any other third-party
                              types, APIGroup is required.
                            type: string
                          kind:
                            description: Kind is the type of resource being referenced
                            type: string
                          name:
                            description: Name is the name of resource being referenced
                            type: string
                        required:
                        - kind
                        - name
                        type: object
                      insecure:
                        description: Insecure is to be set to true if NSX-T uses self-signed
                          cert
                        type: boolean
                      podRoutingEnabled:
                        default: false
                        description: A flag that enables pod routing
                        type: boolean
                      remoteAuth:
                        description: RemoteAuth is to be set to true if NSX-T uses
                          remote authentication (authentication done through the vIDM)
                        type: boolean
                      rootCAData:
                        description: The certificate authority for the server certificate
                          for locally signed certificates
                        type: string
                      route:
                        description: Route configuration for NSXT
                        properties:
                          routerPath:
                            description: NSX-T T0/T1 logical router path
                            type: string
                        type: object
                      vmcAccessToken:
                        description: VMCAccessToken is VMC access token for token
                          based authentication
                        type: string
                      vmcAuthHost:
                        description: VMCAuthHost is VMC verification host for token
                          based authentication
                        type: string
                    type: object
                  proxy:
                    properties:
                      http_proxy:
                        description: HTTP proxy setting
                        type: string
                      https_proxy:
                        description: HTTPS proxy setting
                        type: string
                      no_proxy:
                        description: No-proxy setting
                        type: string
                    type: object
                  region:
                    description: The region used by vSphere multi-AZ feature
                    type: string
                  tlsCipherSuites:
                    default: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                    description: External arguments for cloud provider
                    type: string
                  tlsThumbprint:
                    description: The cryptographic thumbprint of the vSphere endpoint's
                      certificate. Default value is "".
                    type: string
                  vCenterAPIEndpoint:
                    description: The IP address or FQDN of the vSphere endpoint
                    type: string
                  vSphereCredentialLocalObjRef:
                    description: A secret reference that contains vSphere login credentials
                      to access a vSphere endpoint consists of the fields username
                      and password
                    properties:
                      apiGroup:
                        description: APIGroup is the group for the resource being
                          referenced. If APIGroup is not specified, the specified
                          Kind must be in the core API group. For any other third-party
                          types, APIGroup is required.
                        type: string
                      kind:
                        description: Kind is the type of resource being referenced
                        type: string
                      name:
                        description: Name is the name of resource being referenced
                        type: string
                    required:
                    - kind
                    - name
                    type: object
                  vmNetwork:
                    properties:
                      excludeExternalSubnetCidr:
                        description: External VM network CIDR to be excluded
                        type: string
                      excludeInternalSubnetCidr:
                        description: Internal VM network CIDR to be excluded
                        type: string
                      external:
                        description: External VM network name
                        type: string
                      internal:
                        description: Internal VM network name
                        type: string
                    type: object
                  zone:
                    description: The zone used by vSphere multi-AZ feature
                    type: string
                type: object
            required:
            - vsphereCPI
            type: object
          status:
            description: VSphereCPIConfigStatus defines the observed state of VSphereCPIConfig
            properties:
              secretRef:
                description: Name of the data value secret created by vSphere CPI
                  controller
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
