#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tanzu-capabilities-manager
  name: tanzu-capabilities-manager-sa
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "capabilities.run.tanzu.vmware.com/serviceaccount"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-capabilities-manager-clusterrole
  annotations:
    kapp.k14s.io/change-group: "capabilities.run.tanzu.vmware.com/serviceaccount"
rules:
  - apiGroups:
      - run.tanzu.vmware.com
    resources:
      - capabilities
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - run.tanzu.vmware.com
    resources:
      - capabilities/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.tanzu.vmware.com
    resources:
      - capabilities
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.tanzu.vmware.com
    resources:
      - capabilities/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - run.tanzu.vmware.com
    resources:
      - tanzukubernetesreleases
      - tanzukubernetesreleases/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-capabilities-manager-clusterrolebinding
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting capabilities.run.tanzu.vmware.com/serviceaccount"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-capabilities-manager-clusterrole
subjects:
  - kind: ServiceAccount
    name: tanzu-capabilities-manager-sa
    namespace: #@ data.values.namespace
