apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
  #! featuregates
  - image: featuregates-controller-manager:latest
    newImage: ""
  #! capabilities
  - image: capabilities-controller-manager:latest
    newImage: ""
  #! Core-Management-Plugins images
  #! tanzu-cliplugins linux-amd64
  - image: tanzu-cli-plugins/cluster-linux-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/kubernetes-release-linux-amd64:latest
    newImage: ""
  #! tanzu-cliplugins darwin-amd64
  - image: tanzu-cli-plugins/cluster-darwin-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/kubernetes-release-darwin-amd64:latest
    newImage: ""
  #! tanzu-cliplugins windows-amd64
  - image: tanzu-cli-plugins/cluster-windows-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/kubernetes-release-windows-amd64:latest
    newImage: ""
  #! addons-manager
  - image: addons-controller:latest
    newImage: ""
  #! Standalone-Plugins images
  #! tanzu-cliplugins linux-amd64
  - image: tanzu-cli-plugins/login-linux-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/management-cluster-linux-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/package-linux-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/pinniped-auth-linux-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/secret-linux-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/feature-linux-amd64:latest
    newImage: ""
  #! tanzu-cliplugins darwin-amd64
  - image: tanzu-cli-plugins/login-darwin-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/management-cluster-darwin-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/package-darwin-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/pinniped-auth-darwin-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/secret-darwin-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/feature-darwin-amd64:latest
    newImage: ""
  #! tanzu-cliplugins windows-amd64
  - image: tanzu-cli-plugins/login-windows-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/management-cluster-windows-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/package-windows-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/pinniped-auth-windows-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/secret-windows-amd64:latest
    newImage: ""
  - image: tanzu-cli-plugins/feature-windows-amd64:latest
    newImage: ""
  #! tkr-infra-machine-webhook image
  #! The docker image would be same for all the providers
  - image: tkr-infra-machine-webhook:latest
    newImage: ""
  #! tkr-resolver-cluster-webhook image
  - image: tkr-resolver-cluster-webhook:latest
    newImage: ""
  - image: tkr-conversion-webhook:latest
    newImage: ""
