name: Post Cluster Generation Results As Comment

# Adapted from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: ["Provider Template Tests"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6.3.3
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "clustergen-output"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/clustergen-output.zip', Buffer.from(download.data));

      - name: Read artifact info
        shell: bash
        run: |
          unzip clustergen-output.zip
          echo "##[set-output name=diffstatus;]$(cat ./clustergen.status)"
          echo "##[set-output name=prnum;]$(cat ./prnum)"
        id: read_artifact

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmmss'

      - id: upload-clustergen-results
        if: ${{ steps.read_actifact.outputs.diffstatus == 0 }}
        uses: google-github-actions/upload-cloud-storage@v1.0.0
        with:
          path: .
          destination: tkg-clustergen/${{ steps.read_artifact.outputs.prnum }}/${{ steps.time.outputs.time }}
          credentials: ${{ secrets.GCP_BUCKET_SA }}
          glob: clustergen*.diff.txt

      - id: upload-clustergen-results2
        if: ${{ steps.clustergen.outputs.diffstatus == 0 }}
        uses: google-github-actions/upload-cloud-storage@v1.0.0
        with:
          path: ./clustergen.html
          destination: tkg-clustergen/${{ steps.read_artifact.outputs.prnum }}/${{ steps.time.outputs.time }}
          credentials: ${{ secrets.GCP_BUCKET_SA }}

      - name: Create comment with diffs
        if: ${{ steps.read_actifact.outputs.diffstatus == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.read_artifact.outputs.prnum }}
          body: |
            Cluster Generation A/B Results:
            https://storage.googleapis.com/tkg-clustergen/${{ steps.read_artifact.outputs.prnum }}/${{ steps.time.outputs.time }}/clustergen.diff.txt
            Author/reviewers:
            Please review to verify that the effects on the generated cluster configurations are exactly what the PR intended, and give a thumbs-up if so.

      - name: Create comment indicating no changes detected
        if: ${{ steps.read_actifact.outputs.diffstatus != 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.read_artifact.outputs.prnum }}
          body: |
            Cluster Generation A/B Results: (no changes detected)

