name: Test Release Artifacts on Windows OS

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version that has to be tested"
        required: true

jobs:
  release-gate-macos-and-linux-release-builds:
    name: Test Release Artifacts on Windows OS
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'vmware-tanzu/tanzu-framework'
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test Release Artifacts on Windows OS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\hack\test-release-artifacts.ps1 -version ${{ github.event.inputs.release_version }} -signToolPath "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool.exe"

